# Implementing Random forest classifier

In [1]:
# import the libraries
import pandas as pd
import numpy as np

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
# Load the dataset
data = pd.read_csv('Dataset.csv')

In [4]:
data.head()

,GENDER,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN,LUNG_CANCER
0,M,69,1,2,2,1,1,2,1,2,2,2,2,2,2,YES
1,M,74,2,1,1,1,2,2,2,1,1,1,2,2,2,YES
2,F,59,1,1,1,2,1,2,1,2,1,2,2,1,2,NO
3,M,63,2,2,2,1,1,1,1,1,2,1,1,2,2,NO
4,F,63,1,2,1,1,1,1,1,2,1,2,2,1,1,NO

In [5]:
data.columns

Index(['GENDER', 'AGE', 'SMOKING', 'YELLOW_FINGERS', 'ANXIETY',
       'PEER_PRESSURE', 'CHRONIC DISEASE', 'FATIGUE ', 'ALLERGY ', 'WHEEZING',
       'ALCOHOL CONSUMING', 'COUGHING', 'SHORTNESS OF BREATH',
       'SWALLOWING DIFFICULTY', 'CHEST PAIN', 'LUNG_CANCER'],
      dtype='object')

In [6]:
df = data.rename({'ALCOHOL CONSUMING':'Alcohol_Consuming','CHRONIC DISEASE':'Chronic_disease','SHORTNESS OF BREATH':'Shortness_of_breath',
          'SWALLOWING DIFFICULTY':'Swallowing_difficulty','CHEST PAIN':'chest_pain','GENDER':'Gender','AGE':'Age','SMOKING':'Smoking',
          'YELLOW_FINGERS':'Yellow_fingers','ANXIETY':'Anxiety','PEER_PRESSURE':'Peer_pressure','FATIGUE ':'Fatigue','ALLERGY ':'Allergy',
          'WHEEZING':'Wheezing','COUGHING':'Coughing','LUNG_CANCER':'Lung_cancer'},axis=1)

In [7]:
df.columns

Index(['Gender', 'Age', 'Smoking', 'Yellow_fingers', 'Anxiety',
       'Peer_pressure', 'Chronic_disease', 'Fatigue', 'Allergy', 'Wheezing',
       'Alcohol_Consuming', 'Coughing', 'Shortness_of_breath',
       'Swallowing_difficulty', 'chest_pain', 'Lung_cancer'],
      dtype='object')

In [8]:
df.head()

,Gender,Age,Smoking,Yellow_fingers,Anxiety,Peer_pressure,Chronic_disease,Fatigue,Allergy,Wheezing,Alcohol_Consuming,Coughing,Shortness_of_breath,Swallowing_difficulty,chest_pain,Lung_cancer
0,M,69,1,2,2,1,1,2,1,2,2,2,2,2,2,YES
1,M,74,2,1,1,1,2,2,2,1,1,1,2,2,2,YES
2,F,59,1,1,1,2,1,2,1,2,1,2,2,1,2,NO
3,M,63,2,2,2,1,1,1,1,1,2,1,1,2,2,NO
4,F,63,1,2,1,1,1,1,1,2,1,2,2,1,1,NO

In [9]:
df.size

4944

In [10]:
df.dropna()

,Gender,Age,Smoking,Yellow_fingers,Anxiety,Peer_pressure,Chronic_disease,Fatigue,Allergy,Wheezing,Alcohol_Consuming,Coughing,Shortness_of_breath,Swallowing_difficulty,chest_pain,Lung_cancer
0,M,69,1,2,2,1,1,2,1,2,2,2,2,2,2,YES
1,M,74,2,1,1,1,2,2,2,1,1,1,2,2,2,YES
2,F,59,1,1,1,2,1,2,1,2,1,2,2,1,2,NO
3,M,63,2,2,2,1,1,1,1,1,2,1,1,2,2,NO
4,F,63,1,2,1,1,1,1,1,2,1,2,2,1,1,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
304,F,56,1,1,1,2,2,2,1,1,2,2,2,2,1,YES
305,M,70,2,1,1,1,1,2,2,2,2,2,2,1,2,YES
306,M,58,2,1,1,1,1,1,2,2,2,2,1,1,2,YES
307,M,67,2,1,2,1,1,2,2,1,2,2,2,1,2,YES
308,M,62,1,1,1,2,1,2,2,2,2,1,1,2,1,YES

In [11]:
df.describe()

,Age,Smoking,Yellow_fingers,Anxiety,Peer_pressure,Chronic_disease,Fatigue,Allergy,Wheezing,Alcohol_Consuming,Coughing,Shortness_of_breath,Swallowing_difficulty,chest_pain
count,309.000000,309.000000,309.000000,309.000000,309.000000,309.000000,309.000000,309.000000,309.000000,309.000000,309.000000,309.000000,309.000000,309.000000
mean,62.673139,1.563107,1.569579,1.498382,1.501618,1.504854,1.673139,1.556634,1.556634,1.556634,1.579288,1.640777,1.469256,1.556634
std,8.210301,0.496806,0.495938,0.500808,0.500808,0.500787,0.469827,0.497588,0.497588,0.497588,0.494474,0.480551,0.499863,0.497588
min,21.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,57.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
50%,62.000000,2.000000,2.000000,1.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,1.000000,2.000000
75%,69.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000
max,87.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000

In [12]:
# Label encode the dataset
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

var = ['Lung_cancer','Gender']

for i in var:
    df[i] = le.fit_transform(df[i]).astype(int)

In [13]:
#preprocessing, split test and dataset, split response variable
X = df.drop(labels='Lung_cancer', axis=1)
#Response variable
Y = df.loc[:,'Lung_cancer']

In [14]:
import imblearn
from imblearn.over_sampling import RandomOverSampler
from collections import Counter

ros =RandomOverSampler(random_state=1)
x_ros,y_ros=ros.fit_resample(X,Y)
print("OUR DATASET COUNT         : ", Counter(Y))
print("OVER SAMPLING DATA COUNT  : ", Counter(y_ros))

OUR DATASET COUNT         :  Counter({1: 270, 0: 39})
OVER SAMPLING DATA COUNT  :  Counter({1: 270, 0: 270})

In [15]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_ros, y_ros, test_size=0.20, random_state=1, stratify=y_ros)
print("Number of training dataset : ", len(x_train))
print("Number of test dataset     : ", len(x_test))
print("Total number of dataset    : ", len(x_train)+len(x_test))

Number of training dataset :  432
Number of test dataset     :  108
Total number of dataset    :  540

Random forest classifier

In [16]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score,plot_confusion_matrix
from sklearn.ensemble import RandomForestClassifier

Training

In [17]:
RFC = RandomForestClassifier()
RFC.fit(x_train,y_train)
predictRFC =RFC.predict(x_test)

Finding the accuracy of Decision Tree

In [18]:
accuracy = accuracy_score(y_test, predictRFC)
print("Accuracy of Random forest classifier:", accuracy *100)

Accuracy of Random forest classifier: 97.22222222222221

Find the classification report

In [19]:
cr = classification_report(y_test, predictRFC)
print("Classification report \n\n:", cr)

Classification report

:               precision    recall  f1-score   support

           0       0.95      1.00      0.97        54
           1       1.00      0.94      0.97        54

    accuracy                           0.97       108
   macro avg       0.97      0.97      0.97       108
weighted avg       0.97      0.97      0.97       108

Finding the classfication report

In [20]:
cm = confusion_matrix(y_test, predictRFC)
print("Confusion matrix:", cm)

Confusion matrix: [[54  0]
 [ 3 51]]